In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_csv('weather_classification_data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
y = y.reshape(-1,1)

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ctx = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output= False), [4,7,9])], remainder='passthrough')
X = np.array(ctx.fit_transform(X))
cty = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output= False), [0])], remainder='passthrough')
y = np.array(cty.fit_transform(y))
#print(X)
#print(y)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 11:] = sc.fit_transform(X_train[:, 11:])
X_test[:, 11:] = sc.transform(X_test[:,11:])
X_test = np.array(X_test).astype('float32')


In [15]:
ann = tf.keras.models.Sequential()

In [16]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

In [17]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=4, activation='softmax'))

In [19]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.2884 - loss: 1.3538
Epoch 2/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6327 - loss: 0.9764
Epoch 3/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8212 - loss: 0.6269
Epoch 4/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8772 - loss: 0.4616
Epoch 5/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8821 - loss: 0.4140
Epoch 6/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8798 - loss: 0.4078
Epoch 7/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8843 - loss: 0.3709
Epoch 8/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8855 - loss: 0.3656
Epoch 9/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8845 - loss: 0.3535
Epoch 10/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8876 - loss: 0.3272
Epoch 11/100
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8911 - loss: 0.3258
Epoch 12/100
310/310 ━━━━━━━━━━━━━━━━━━━━

In [21]:
y_pred = ann.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=1)
if y_test.ndim > 1:
    y_test_labels = np.argmax(y_test, axis=1)
else:
    y_test_labels = y_test

104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test_labels, y_pred_labels)
print(cm)
accuracy_score(y_test_labels,y_pred_labels)

[[796  36   0  10]
 [ 94 738   5   9]
 [ 54   7 752   7]
 [ 83  10   4 695]]


0.9033333333333333